name: Discord Weekly Schedule

on:
  schedule:
    # Runs every Monday at 1:00 p.m. UTC    
# 1:00 p.m. UTC is 10:00 a.m. in Argentina (current local time)
    - cron: '0 13 * * 1'
  workflow_dispatch: # This command lets you run the bot manually from GitHub using a button to test it

jobs:
  send_message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # We use a recent version that includes native Fetch
          
      - name: Ejecutar script de Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
        run: node script.js
